# Generated by Django 2.2.5 on 2019-09-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('price', models.FloatField(db_index=True, default=0)),
                ('images', models.ImageField(upload_to='')),
                ('deyer', models.PositiveIntegerField(choices=[(1, 'bahali'), (2, 'orta'), (3, 'ucuz')])),
            ],
        ),
    ]
