# Generated by Django 2.2.5 on 2019-09-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_app', '0002_auto_20190916_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(upload_to='users'),
        ),
    ]
