# Generated by Django 2.2.5 on 2019-09-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0001_initial'),
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
