# Generated by Django 2.2.5 on 2019-09-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20190916_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published_at',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author_app.Author'),
        ),
    ]
